# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('proof-of-stake-testbed-example', ['proof-of-stake-testbed'])
    obj.source = 'proof-of-stake-testbed-example.cc'

